version: '3.9'

services:
  uvicorn_trt_server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: uvicorn_trt_server
    environment:
      - MILVUS_HOST=standalone
      - MILVUS_PORT=19530
    shm_size: 2gb
    ulimits:
      stack: 67108864
      memlock: -1
    ports:
      - 8080:8080

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    expose:
      - "9001"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.2
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    expose:
      - "19530"
    depends_on:
      - "etcd"
      - "minio"

  mysql:
    container_name: mariadb
    image: mariadb:10.3
    restart: always
    env_file: ./.env
    expose:
      - "3306"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/store:/var/lib/mysql
    mem_limit: 512m
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER="${PMA_USER}"
      - PMA_PASSWORD="${PMA_PASSWORD}"

  mysql-admin:
    container_name: mariadb-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file: ./.env
    ports:
      - "8001:80"
    mem_limit: 512m
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER="${PMA_USER}"
      - PMA_PASSWORD="${PMA_PASSWORD}"

  redis-server:
    container_name: redis-server
    image: redis:7.0.8
    restart: always
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    expose:
      - "6379"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/redis:/data
    mem_limit: 96m

networks:
  default:
    name: face_recog_milvus
