version:  '3.3'
services:
  uvicorn_trt_server:
    build:
      context: server
      dockerfile: ./Dockerfile
    container_name: uvi_trt_server
    shm_size: 2gb
    ulimits:
      stack: 67108864
      memlock: -1
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ports:
      - 8000:8080

  elasticsearch_server:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  data01:
    driver: local

networks:
  face_recog_elastic:
    driver: bridge
